### ISSUE TITLE
Logstash 2.3 support?

### ISSUE THREAD

**Issue by gdhbashton** [tootedom/logstash_dropwizard_metrics_stats#1]
Hi - I tried to make this run on Logstash 2.3 without much luck. After writing a gemspec and building the module, a simple config causes the plugin to explode:

```
input {
    dropwizard_metrics_stats {
       url => "http://localhost:8083/metrics"
       store_all_keys => true
       poll_period_s => 20
       request_timeout_s => 5
    }
}
```

```
{:timestamp=>"2016-05-03T10:41:36.824000+0000", :message=>"Failed to get metrics from app /metrics, due to unexpected exception, retrying connection in 5 seconds", :name=>nil, :exception=>#<NameError: uninitialized constant LogStash::Inputs::DropwizardMetricsStats::JSON>, :backtrace=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/opt/logstash/vendor/local_gems/2127e5cf/logstash-input-dropwizardmetrics-1.0.0/lib/logstash/inputs/dropwizard_metrics_stats.rb:80:in `handle_request'", "/opt/logstash/vendor/local_gems/2127e5cf/logstash-input-dropwizardmetrics-1.0.0/lib/logstash/inputs/dropwizard_metrics_stats.rb:215:in `run_client'", "/opt/logstash/vendor/local_gems/2127e5cf/logstash-input-dropwizardmetrics-1.0.0/lib/logstash/inputs/dropwizard_metrics_stats.rb:190:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn}
```

**Comment by tootedom** [comment]
Hi there,

I wrote this plugin way back in 2014, I think even before logstash 1.5 or 1.4.  I very much doubt it works in 2.x.   I've not used it in 1.5 either, as we pretty much ditched the idea of sending the DW metrics into kibana, and instead send the dropwizard metrics into riemann, which we then aggregate and post to hosted graphite.

not much I can say other than rewrite the entire thing to work with logstash 2.x
/dom

**Comment by gdhbashton** [comment]
Ah that's a shame.

With the advent of Timelion providing decent time-series support for the ELK stack (wow, a derivative() function!) I hoped you might be interested in updating it. I don't have those skills so I'll adopt another approach (DropWizard's own Graphite metrics reporter to a `graphite {}` input on localhost)

Thanks for the reply :)
